templateDir: templates/server
additionalProperties:
  settings:
    base:
      - { "key": Testing, "value": "False" }
    development:
      - { "key": SQLALCHEMY_DATABASE_URI, "value": '"sqlite:///project.db"' }
    testing:
      - { "key": SQLALCHEMY_DATABASE_URI, "value": '"sqlite:///test.db"' }
      - { "key": Testing, "value": "True" }
files:
  __init__main.mustache:
    destinationFilename: openapi_server/__init__.py
    templateType: SupportingFiles
  config.mustache:
    destinationFilename: openapi_server/config.py
    templateType: SupportingFiles
  handlers.mustache:
    destinationFilename: openapi_server/handlers/handlers_temp.py
    templateType: SupportingFiles
  __init__handlers.mustache:
    destinationFilename: openapi_server/handlers/__init__.py
    templateType: SupportingFiles
  __init__database.mustache:
    destinationFilename: openapi_server/database/__init__.py
  database.mustache:
    destinationFilename: openapi_server/database/database.py
  database-model.mustache:
    destinationFilename: openapi_server/database/models.py
  conftest.mustache:
    destinationFilename: openapi_server/test/conftest.py
